pipeline {
    agent any
    stages {
        stage('Newman tests') {
            steps {
                sh '''
                node --
                cd api
                cd newman
                newman run examen.postman_collection.json -e examen.postman_environment.json
                '''
            }
        }
    
    }
    stages {
        stage('Jmeter tests') {
            steps {
                sh '''
               
                cd load
                jmeter -n -t examen_carga.jmx
                '''
            }
        }
    
    }
}
