pipeline {
    agent any
    stages {
        stage('Newman tests') {
            steps {
                sh '''
                cd api
                cd newman
                newman run examen.postman_collection.json -e examen.postman_environment.json 
                '''
            }
        }
    
    }
}
